name: "@madfish/hello_python"
version: "0.0.1"
description: "Pure-Python Hello World plugin (panel + operator)"

# fully-qualified operator names
operators:
  - "@madfish/hello_python/print_me"

# fully-qualified panel class name
panels:
  - "@madfish/hello_python.HelloPanel"
